title: 잡담이 코드가 될 때
description: 친구와의 대화, AI와의 협업, 컨퍼런스에서 배운 것들
tagline: 친구와의 대화, AI와의 협업, 컨퍼런스에서 배운 것들
url: "https://keepConcentration.github.io"
baseurl: ""
timezone: Asia/Seoul
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - sketches
google_site_verification: 7mfS9v-IJh0NeuQGkaRWR-iaCMVVJ2B6fRlvM-N8ERo
